spring.application.name=firstjobappcompanyandreviews

#H2 Database
# spring.h2.console.enabled=true
# spring.datasource.url=jdbc:h2:mem:sochtech
# spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=update

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/jobapp
spring.datasource.username=sochtech254
spring.datasource.password=sochtech254
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# info
info.app.name=JobApplication
info.app.description=Job app built by sochtech
info.app.version=1.0.0

management.info.env.enabled=true